/* Generated By:JavaCC: Do not edit this line. Compilador.java */
package MiniLeng;
import Util.Simbolo;
import Util.Simbolo.Tipo_simbolo;
import Util.Simbolo.Tipo_variable;
import Util.Simbolo.Clase_parametro;
import Util.Tabla_Simbolos;
import Util.TablaHash;
import Util.RegistroExp;
import Util.Etiqueta;
import Util.TipoOperador;
import Util.TipoOperador.Tipo_Operador_Aditivo;
import Util.TipoOperador.Tipo_Operador_Multiplicativo;
import Util.TipoOperador.Tipo_Operador_Relacional;
import Exceptions.ErrorLexico;
import Exceptions.ErrorSemantico;
import Exceptions.ErrorSintactico;
import Warnings.DesbordamientoEnteros;
import java.io.File;
import java.io.IOException;
import java.util.LinkedList;
import java.io.FileWriter;
import java.io.PrintWriter;

public class Compilador implements CompiladorConstants {
  public static int nivel = 0;

  static final int DIRECCION_INICIAL = 3;
  static final int RETORNO_CARRO = 10;
  static final int SALTO_LINEA = 13;
  static final int TABULADOR = 9;

  public static long dir = DIRECCION_INICIAL;

  public static PrintWriter pw;

  public static Tabla_Simbolos tabla = new Tabla_Simbolos();

  public static Etiqueta etiq = new Etiqueta();

  public static ErrorLexico eL = new ErrorLexico();

  public static boolean flag_invocacion = false;

  public static boolean derechaAsig = false;

  public static void iniciar_pila()
  {
    dir = DIRECCION_INICIAL;
  }

  public static void incrementar_pila()
  {
    dir++;
  }

  public static void main(String args []) throws ParseException, IOException
  {
    String nombreArchivo;
    String path = "C:\u005c\u005cUsers\u005c\u005cGord\u005c\u005cDesktop\u005c\u005cprogramas\u005c\u005c";
    if (args [0].equals("-v"))
    {
      System.out.println("Compilacion en modo verbose");
      nombreArchivo = args [1];
    }
    else
    {
      System.out.println("Compilacion sin modo verbose");
      nombreArchivo = args [0];
    }
    File ficheroSalida = new File("C:\u005c\u005cUsers\u005c\u005cGord\u005c\u005cDesktop\u005c\u005cprogramas\u005c\u005c" + nombreArchivo + ".code");
    FileWriter ficheroCode = new FileWriter(ficheroSalida);
    pw = new PrintWriter(ficheroCode);

    path += nombreArchivo + ".ml";
    System.out.println("LEYENDO FICHERO " + nombreArchivo + "\u005cn");
    try
    {
      Compilador parser = new Compilador(new java.io.FileInputStream(path));
      tabla.inicializar_tabla();
      int res = Compilador.programa();
      if (args [0].equals("-v"))
      {
        TablaHash.mostrarTokensNormales();
        TablaHash.mostrarIdentificadores();
      }
      ficheroCode.close();
      int erroresLexicos = ErrorLexico.getNumErroresLexicos();
      int erroresSintacticos = ErrorSintactico.getNumErroresSintacticos();
      int erroresSemanticos = ErrorSemantico.getNumErroresSemanticos();
      if (erroresLexicos > 0 || erroresSintacticos > 0 || erroresSemanticos > 0)
      {
        System.out.println("Compilacion finalizada con errores");
        System.out.println("==================================");
        System.out.println("Detectados " + erroresLexicos + " errores lexicos");
        System.out.println("Detectados " + erroresSintacticos + " errores sintacticos");
        System.out.println("Detectados " + erroresSemanticos + " errores semanticos");
        ficheroSalida.delete();
      }
      else
      {
        System.out.println("Compilacion finalizada sin errores");
        System.out.println("==================================");
        System.out.println("El fichero " + nombreArchivo + " es correcto");
      }
    }
    catch (Exception e)
    {
      System.out.println("INCORRECTO");
      System.out.println(e.getMessage());
      Compilador.ReInit(System.in);
    }
    catch (Error e)
    {
      int fila = CompiladorTokenManager.input_stream.getBeginLine();
      int columna = CompiladorTokenManager.input_stream.getBeginColumn();
      String tokenMalo = CompiladorTokenManager.input_stream.GetImage();
      ErrorLexico.deteccionErrorLexico(fila, columna, tokenMalo);
    }
  }

/* Construccion del analizador sintactico */
  static final public int programa() throws ParseException {
  Token tSim, t;
  Simbolo s;
  Simbolo.Tipo_simbolo tp_Sim;
    try {
      jj_consume_token(tPROGRAMA);
      t = jj_consume_token(tIDENTIFICADOR);
      s = tabla.introducir_programa(t.image, dir);
      pw.println("; Programa " + t.image.toUpperCase() + ".");
      String etiquetaProg = etiq.nueva_etiqueta();
      pw.println("\u005ct ENP  " + etiquetaProg);
      jj_consume_token(tPUNTYCOM);
      declaracion_variables();
      declaracion_acciones();
      pw.println("; Comienzo del programa " + t.image.toUpperCase());
      pw.println(etiquetaProg + ":");
      bloque_sentencias(s);
      pw.println("; Fin del programa " + t.image.toUpperCase() + ".");
      pw.println("\u005ct LVP");
      jj_consume_token(0);
      {if (true) return 0;}
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    {if (true) return 1;}
    }
    throw new Error("Missing return statement in function");
  }

  static final public void bloque_sentencias(Simbolo s) throws ParseException {
  LinkedList<Simbolo> listaAuxiliar = new LinkedList<Simbolo>();
  Simbolo par;
    try {
      pw.println("; Accion " + s.getNombre().toUpperCase() + ".");

      if (!s.es_Simbolo_Programa())
      {
        pw.println(s.getEtiqueta() + ":");
      }
      listaAuxiliar = s.getLista_parametros();
      for (int j = listaAuxiliar.size() - 1; j >= 0; j--)
      {
         par = listaAuxiliar.get(j);
         pw.println("; rec. parametro " + par.getNombre().toUpperCase() + " de tipo " + par.getVariable().toString() +
         " pasado por " + par.getParametro().toString());
         pw.println("\u005ct SRF   " + (nivel - par.getNivel()) + "  " + par.getDir());
         pw.println("\u005ct ASGI");
      }
      jj_consume_token(tPRINCIPIO);
      lista_sentencias();
      jj_consume_token(tFIN);
      tabla.ocultar_parametros(nivel);
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
  }

  static final public void lista_sentencias() throws ParseException {
    try {
      label_1:
      while (true) {
        sentencia();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tSI:
        case tMQ:
        case tESCRIBIR:
        case tLEER:
        case tIDENTIFICADOR:
          ;
          break;
        default:
          jj_la1[0] = jj_gen;
          break label_1;
        }
      }
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
  }

  static final public void sentencia() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tLEER:
        leer();
        jj_consume_token(tPUNTYCOM);
        break;
      case tESCRIBIR:
        escribir();
        jj_consume_token(tPUNTYCOM);
        break;
      case tIDENTIFICADOR:
        asig_invoc();
        break;
      case tSI:
        seleccion();
        break;
      case tMQ:
        mientras_que();
        break;
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
  }

  static final public void asig_invoc() throws ParseException {
  Token t;
    try {
      t = jj_consume_token(tIDENTIFICADOR);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tOPAS:
        asignacion(t);
        break;
      case tPUNTYCOM:
      case tPARENTESIS_IZDA:
        invocacion_accion(t);
        break;
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
  }

  static final public void asignacion(Token t) throws ParseException {
  RegistroExp tpExp;
  Simbolo s;
  Simbolo.Tipo_variable tipo = null;
  boolean ok = true;
    try {
      jj_consume_token(tOPAS);
      s = tabla.buscar_simbolo(t.image);
      if (s == null)
      {
        ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
        ", columna " + token.beginColumn + "  - Variable desconocida " + t.image +
        " en la parte izquierda de la asignacion");
        // Tipo de simbolo desconocido
        tipo = Simbolo.Tipo_variable.DESCONOCIDO;
        ok = false;
      }
      else if (s.es_Simbolo_Parametro())
      {
        if (s.es_Parametro_Valor())
        {
          ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
          ", columna " + token.beginColumn + "  - Prohibido asignar a " + s.getNombre() +
          ", es un parametro pasado como valor");
          tipo = Simbolo.Tipo_variable.DESCONOCIDO;
          ok = false;
        }
        else
        {
          tipo = s.getVariable();
          pw.println("; Direccion del parametro por referencia " + s.getNombre().toUpperCase() + ".");
          pw.println("\u005ct SRF   " + (nivel - s.getNivel()) + "  " + s.getDir());
          pw.println("\u005ct DRF");
          derechaAsig = true;
        }
      }
      else if (s.es_Simbolo_Accion())
      {
        ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
        ", columna " + token.beginColumn + "  - Prohibida la asignacion a la accion " +
        s.getNombre());
        tipo = Simbolo.Tipo_variable.DESCONOCIDO;
        ok = false;
      }
      else
      {
        pw.println("; Direccion de la variable " + s.getNombre().toUpperCase() + ".");
        pw.println("\u005ct SRF   " + (nivel - s.getNivel()) + "  " + s.getDir());
        tipo = s.getVariable();
        derechaAsig = true;
      }
      tpExp = expresion();
      jj_consume_token(tPUNTYCOM);
      if (ok && tpExp.getTipo() != tipo && tpExp.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
      {
        ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
        ", columna " + token.beginColumn + "  - Tipos incompatibles en la asignacion: " +
        "no se puede convetir " + tpExp.getTipo().toString() + " a " + tipo.toString());
      }
      else
      {
        pw.println("; Asignacion.");
        pw.println("\u005ct ASG");
      }
      derechaAsig = false;
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
  }

  static final public void lista_asignables() throws ParseException {
  LinkedList < String > listaIdentificadores;
  String idActual;
    try {
      listaIdentificadores = identificadores();
      int dimension = listaIdentificadores.size();
      Simbolo s;
      for (int i = 0; i < dimension; i++)
      {
        idActual = listaIdentificadores.get(i);
        s = tabla.buscar_simbolo(idActual);
        if (s == null)
        {
          ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
          ", columna " + token.beginColumn + "  - Identificador de asignacion "
          + idActual + " desconocido");
        }
        else if (s.getTipo() == Simbolo.Tipo_simbolo.VARIABLE
        || s.getVariable() == Simbolo.Tipo_variable.DESCONOCIDO)
        {
          if (s.es_Variable_Booleano() || s.es_Variable_Cadena())
          {
            ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
            ", columna " + token.beginColumn + "  - Tipo invalido de variable de lectura, se espera " +
            "entero o caracter");
          }
          else
          {
            pw.println("; Leer variable " + s.getNombre());
            pw.println("\u005ct SRF   " + (nivel - s.getNivel()) + "  " + s.getDir());

            if (s.getVariable() == Simbolo.Tipo_variable.ENTERO)
            {
                pw.println("\u005ct RD    1");
                }
                else
                {
                        pw.println("\u005ct RD    0");
                }
          }
        }
        else if (s.es_Simbolo_Parametro())
        {
          if (s.es_Parametro_Valor())
          {
            ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
            ", columna " + token.beginColumn + "  - Variable " + s.getNombre() +
            " por valor en lectura");
          }
          else
          {
            pw.println("; Leer parametro por referencia " + s.getNombre());
            pw.println("\u005ct SRF   " + (nivel - s.getNivel()) + "  " + s.getDir());
            pw.println("\u005ct DRF");
            if (s.getVariable() == Simbolo.Tipo_variable.ENTERO)
            {
                pw.println("\u005ct RD    1");
                }
                else
                {
                        pw.println("\u005ct RD    0");
                }
          }
        }
        else if (s.es_Simbolo_Accion())
        {
          ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
          ", columna " + token.beginColumn + "  - Los argumentos de una funcion solo pueden ser" +
          " parametros o variables, encontrado " + s.getNombre() + " de tipo " + s.getTipo().toString());
        }
      }
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
  }

  static final public void leer() throws ParseException {
    try {
      jj_consume_token(tLEER);
      pw.println("; Lectura");
      jj_consume_token(tPARENTESIS_IZDA);
      lista_asignables();
      jj_consume_token(tPARENTESIS_DCHA);
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
  }

  static final public void escribir() throws ParseException {
    try {
      jj_consume_token(tESCRIBIR);
      pw.println("; Escritura");
      jj_consume_token(tPARENTESIS_IZDA);
      lista_escribibles();
      jj_consume_token(tPARENTESIS_DCHA);
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
  }

  static final public void lista_escribibles() throws ParseException {
    try {
      escribible();
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tCOMA:
          ;
          break;
        default:
          jj_la1[3] = jj_gen;
          break label_2;
        }
        jj_consume_token(tCOMA);
        escribible();
      }
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
  }

  static final public void escribible() throws ParseException {
  Token t = null;
  Simbolo s;
  RegistroExp regExp = null;
  RegistroExp result = new RegistroExp();
  boolean constCad = false, entCad = false, caracter_especial = false;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tCONSTCHAR:
        t = jj_consume_token(tCONSTCHAR);
      constCad = true;
        break;
      case tCONSTCAD:
        t = jj_consume_token(tCONSTCAD);
      constCad = true;
        break;
      case tIDENTIFICADOR:
        t = jj_consume_token(tIDENTIFICADOR);
        break;
      case tENTACAR:
        jj_consume_token(tENTACAR);
        jj_consume_token(tPARENTESIS_IZDA);
        regExp = expresion();
        jj_consume_token(tPARENTESIS_DCHA);
      entCad = true;
        break;
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      if (constCad)
      {
        String cad = t.image.replace("\u005c"", "'");
        pw.println("; cadena " + cad + ".");
        String cadena = t.image;
        int tamanyo = cadena.length();
        for (int i = 1; i < tamanyo - 1; i++)
        {
          if (cadena.charAt(i) == '\u005c\u005c')
          {
            caracter_especial = true;
          }
          else if ((cadena.charAt(i) == 'n') && caracter_especial)
          {
                pw.println("\u005ct STC   10" );
                pw.println("\u005ct WRT   0");
                caracter_especial = false;
          }
          else if ((cadena.charAt(i) == 'r') && caracter_especial)
          {
                pw.println("\u005ct STC   13" );
                pw.println("\u005ct WRT   0");
                caracter_especial = false;
          }
          else if ((cadena.charAt(i) == 't') && caracter_especial)
          {
                pw.println("\u005ct STC   9" );
                pw.println("\u005ct WRT   0");
                caracter_especial = false;
          }
          else
          {
            pw.println("\u005ct STC   " + (int)cadena.charAt(i));
                pw.println("\u005ct WRT   0");
                caracter_especial = false;
          }
        }
        result.setTipo(Simbolo.Tipo_variable.CADENA);
      }
      else if (entCad)
      {
        if (regExp.getTipo() != Simbolo.Tipo_variable.ENTERO)
        {
          ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
          ", columna " + token.beginColumn + "  - Se esperaba una expresion del tipo" +
          " ENTERO en la funcion entacar. Se ha recibido una expresion de tipo " +
          regExp.getTipo().toString());
        }
        else
        {
          if (regExp.valorEnt == RETORNO_CARRO || regExp.valorEnt == SALTO_LINEA)
          {
            pw.println("\u005ct WRT   0");
          }
          else
          {
                pw.println("\u005ct WRT   1");
          }
          result.setTipo(Simbolo.Tipo_variable.ENTERO);
        }
      }
      else
      {
        s = tabla.buscar_simbolo(t.image);
        if (s == null)
        {
          ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
          ", columna " + token.beginColumn + "  - Variable a escribir " + s.getNombre()
          + " desconocida ");
        }
        else if (s.es_Variable_Desconocido())
        {
          ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
          ", columna " + token.beginColumn + "  - Variable " + t.image + " no valida para escritura");
        }
        else
        {
          pw.println("; Acceso a la variable " + s.getNombre().toUpperCase() + ".");
          pw.println("\u005ct SRF   " + (nivel - s.getNivel()) + "  " + s.getDir());
          pw.println("\u005ct DRF");

          if (s.es_Simbolo_Parametro() && s.es_Parametro_Referencia())
          {
                pw.println("\u005ct DRF");
          }
          if (s.getVariable() == Simbolo.Tipo_variable.ENTERO)
          {
                pw.println("\u005ct WRT   1");
          }
          if (s.getVariable() == Simbolo.Tipo_variable.CHAR)
          {
            pw.println("\u005ct WRT\u0009 0");
          }
        }
      }
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
  }

  static final public void invocacion_accion(Token t) throws ParseException {
  Simbolo s = null, par = null;
  boolean args = false;
    try {
      flag_invocacion = true;

      s = tabla.buscar_simbolo(t.image);
      if (s == null)
      {
        ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
        ", columna " + token.beginColumn + "  - Identificador " + t.image +
        " desconocido en llamada a accion");
      }
      else if (!s.es_Simbolo_Accion())
      {
        ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
        ", columna " + token.beginColumn + "  - No se puede realizar una llamada" +
        " a una accion sobre el parametro " + t.image);
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tPARENTESIS_IZDA:
        argumentos(s);
      args = true;
        break;
      default:
        jj_la1[5] = jj_gen;
        ;
      }
      jj_consume_token(tPUNTYCOM);
      if (s != null)
      {
        int argc = s.getLista_parametros().size();
        if (!args && argc != 0)
        {
          ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
          ", columna " + token.beginColumn + " -  Se esperaban " + argc +
          " parametros al invocar a la accion " + s.getNombre());
        }
        else
        {
          pw.println("; Invocando a " + s.getNombre().toUpperCase());
          pw.println("\u005ct OSF   " + (s.getDir() - 1) + "  " + (nivel - s.getNivel()) + " " + s.getEtiqueta());
        }
      }
      flag_invocacion = false;
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
  }

  static final public void mientras_que() throws ParseException {
  RegistroExp tpExp;
  String etiqMQ, etiqFIN = null;
    try {
      jj_consume_token(tMQ);
      etiqMQ = etiq.nueva_etiqueta();
      pw.println(etiqMQ + ":");
      pw.println("; MQ.");
      tpExp = expresion();
      if ((tpExp.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
      && (tpExp.getTipo() != Simbolo.Tipo_variable.BOOLEANO))
      {
        ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
        ", columna " + token.beginColumn + " - La condicion de mientras_que debe ser booleana");
      }
      else
      {
        etiqFIN = etiq.nueva_etiqueta();
        pw.println("; Salir del bucle si la guarda se evalua a falso.");
        pw.println("\u005ct JMF  " + etiqFIN);
      }
      lista_sentencias();
      jj_consume_token(tFMQ);
      pw.println("; Fin de la iteracion. Saltar a la cabecera del bucle.");
      pw.println("\u005ct JMP  " + etiqMQ);
      pw.println(etiqFIN + ":");
      pw.println("; Fin MQ");
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
  }

  static final public void argumentos(Simbolo s) throws ParseException {
  boolean ok = false;
    try {
      jj_consume_token(tPARENTESIS_IZDA);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tMINUS:
      case tNOT:
      case tTRUE:
      case tFALSE:
      case tENTACAR:
      case tCARAENT:
      case tCONSTCHAR:
      case tCONSTCAD:
      case tCONSTANTE_NUMERICA:
      case tIDENTIFICADOR:
      case tPARENTESIS_IZDA:
        lista_expresiones(s);
      ok = true;
        break;
      default:
        jj_la1[6] = jj_gen;
        ;
      }
      jj_consume_token(tPARENTESIS_DCHA);
      if (s != null)
      {
        int argc = s.getLista_parametros().size();
        if (!ok && argc != 0)
        {
          ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
          " - Se esperaban " + argc + " parametros al invocar a la accion " +
          s.getNombre());
        }
      }
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
  }

  static final public void lista_expresiones(Simbolo s) throws ParseException {
  RegistroExp r;
  int argc = 0;
  boolean ok = true;
  LinkedList < Simbolo > parametros;
    try {
      r = expresion();
      if (s != null && !s.es_Variable_Desconocido())
      {
        parametros = s.getLista_parametros();
        argc++;
        if (argc > parametros.size())
        {
          ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
          ", columna " + token.beginColumn + "  - El numero de parametros de" +
          " llamada a la funcion " + s.getNombre() +
          " no coindice, se esperaban " + parametros.size());
          ok = false;
        }
        else if (r.getTipo() != parametros.get(argc - 1).getVariable())
        {
          ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
          ", columna " + token.beginColumn + "  - Los tipos en la llamada a la funcion " +
          s.getNombre() + " no coindicen");
          ok = false;
        }
        else if (r.getClase() == Simbolo.Clase_parametro.VAL && !parametros.get(argc - 1).es_Parametro_Valor())
        {
          ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
          ", columna " + token.beginColumn + "  - Error al pasar un parametro por valor como referencia");
          ok = false;
        }
        else if (parametros.get(argc - 1).es_Parametro_Referencia() && r.isExpr_compuesta())
        {
          ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
          ", columna " + token.beginColumn + "  - No se puede pasar al parametro por referencia " +
          parametros.get(argc - 1).getNombre() + " una expresion compuesta");
          ok = false;
        }
        else
        {
          if (flag_invocacion && (parametros.get(argc - 1).es_Parametro_Valor())
                  && !r.isExpr_compuesta())
          {
            pw.println("\u005ct DRF");
          }
          ok = false;
        }
      }
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tCOMA:
          ;
          break;
        default:
          jj_la1[7] = jj_gen;
          break label_3;
        }
        jj_consume_token(tCOMA);
        r = expresion();
      if (s != null && !s.es_Variable_Desconocido())
      {
        parametros = s.getLista_parametros();
        argc++;
        if (argc > parametros.size())
        {
          ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
          ", columna " + token.beginColumn + "  - El numero de parametros de" +
          " llamada a la funcion " + s.getNombre() +
          " no coindice, se esperaban " + parametros.size());
          ok = false;
        }
        else if (r.getTipo() != parametros.get(argc - 1).getVariable())
        {
          ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
          ", columna " + token.beginColumn + "  - Los tipos en la llamada a la funcion" +
          s.getNombre() + " no coindicen");
          ok = false;
        }
        else if (r.getClase() == Simbolo.Clase_parametro.VAL && !parametros.get(argc - 1).es_Parametro_Valor())
        {
          ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
          ", columna " + token.beginColumn + "  - Error al pasar un parametro por valor como referencia");
          ok = false;
        }
        else if (parametros.get(argc - 1).es_Parametro_Referencia() && r.isExpr_compuesta())
        {
          ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
          ", columna " + token.beginColumn + "  - No se puede pasar al parametro por referencia " +
          parametros.get(argc - 1).getNombre() + " una expresion compuesta");
          ok = false;
        }
        else
        {
          ok = false;
        }
      }
      }
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
  }

  static final public RegistroExp expresion() throws ParseException {
  RegistroExp tpExp1 = null, tpExp2 = null;
  TipoOperador op;
  boolean ok = true;
  RegistroExp regResult = new RegistroExp();
  boolean constantes = false;
    try {
      tpExp1 = expresion_simple();
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tMAYOR:
        case tMENOR:
        case tIGUAL:
        case tMAI:
        case tMEI:
        case tNI:
          ;
          break;
        default:
          jj_la1[8] = jj_gen;
          break label_4;
        }
        op = operador_relacional();
        tpExp2 = expresion_simple();
      regResult = new RegistroExp();
      if (tpExp1.getTipo() == Simbolo.Tipo_variable.DESCONOCIDO)
      {
        ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
        ", columna " + token.beginColumn + "  - El operador 1 debe ser entero " +
        "caracter, cadena o booleano");
        ok = false;
      }
      if (tpExp2.getTipo() == Simbolo.Tipo_variable.DESCONOCIDO)
      {
        ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
        ", columna " + token.beginColumn + "  - El operador 2 debe ser entero " +
        "caracter, cadena o booleano");
        ok = false;
      }
      if (ok)
      {
        if (tpExp1.getTipo() != tpExp2.getTipo())
        {
          ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
          ", columna " + token.beginColumn + "  - Los operadores deben ser del mismo tipo " +
          " en la expresion " + tpExp1.getTipo().toString() + " : " + tpExp2.getTipo().toString());
          regResult.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
        }
        else
        {
          regResult.setTipo(Simbolo.Tipo_variable.BOOLEANO);
          switch (tpExp1.getTipo())
          {
            case ENTERO :
            ok = tpExp2.getTipo() == Simbolo.Tipo_variable.ENTERO;
            regResult.setTipo(Simbolo.Tipo_variable.BOOLEANO);
            if (!ok)
            {
              regResult.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
            }
            else if (tpExp1.getSimbolo() == Simbolo.Tipo_simbolo.CONST
            && tpExp2.getSimbolo() == Simbolo.Tipo_simbolo.CONST)
            {
              constantes = true;
              regResult.setSimbolo(Simbolo.Tipo_simbolo.CONST);
              switch (op.getOperadorRelacional())
              {
                case MAYOR :
                pw.println("\u005ct GT");
                regResult.valorBool = tpExp1.valorEnt > tpExp2.valorEnt;
                break;
                case MAYOR_IGUAL :
                pw.println("\u005ct GTE");
                regResult.valorBool = tpExp1.valorEnt >= tpExp2.valorEnt;
                break;
                case IGUAL :
                pw.println("\u005ct EQ");
                regResult.valorBool = tpExp1.valorEnt == tpExp2.valorEnt;
                break;
                case NO_IGUAL :
                pw.println("\u005ct NEQ");
                regResult.valorBool = tpExp1.valorEnt != tpExp2.valorEnt;
                break;
                case MENOR_IGUAL :
                pw.println("\u005ct LTE");
                regResult.valorBool = tpExp1.valorEnt <= tpExp2.valorEnt;
                break;
                case MENOR :
                pw.println("\u005ct LT");
                regResult.valorBool = tpExp1.valorEnt < tpExp2.valorEnt;
                break;
                default :
                break;
              }
            }
            else
            {
              switch (op.getOperadorRelacional())
              {
                case MAYOR :
                pw.println("\u005ct GT");
                break;
                case MAYOR_IGUAL :
                pw.println("\u005ct GTE");
                break;
                case IGUAL :
                pw.println("\u005ct EQ");
                break;
                case NO_IGUAL :
                pw.println("\u005ct NEQ");
                break;
                case MENOR_IGUAL :
                pw.println("\u005ct LTE");
                break;
                case MENOR :
                pw.println("\u005ct LT");
                break;
                default :
                break;
              }
            }
            break;
            case CHAR :
            regResult.setTipo(Simbolo.Tipo_variable.BOOLEANO);
            ok = tpExp2.getTipo() == Simbolo.Tipo_variable.CHAR;
            if (!ok)
            {
              regResult.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
            }
            else if (tpExp1.getSimbolo() == Simbolo.Tipo_simbolo.CONST
            && tpExp2.getSimbolo() == Simbolo.Tipo_simbolo.CONST)
            {
              constantes = true;
              switch (op.getOperadorRelacional())
              {
                case IGUAL :
                pw.println("\u005ct EQ");
                regResult.valorBool = tpExp1.valorString.equals(tpExp2.valorString);
                break;
                case NO_IGUAL :
                pw.println("\u005ct NEQ");
                regResult.valorBool = !tpExp1.valorString.equals(tpExp2.valorString);
                case MAYOR_IGUAL :
                pw.println("\u005ct GTE");
                regResult.valorBool = tpExp1.valorString.charAt(0) >= tpExp2.valorString.charAt(0);
                break;
                case MAYOR :
                pw.println("\u005ct GT");
                regResult.valorBool = tpExp1.valorString.charAt(0) > tpExp2.valorString.charAt(0);
                case MENOR :
                pw.println("\u005ct LTE");
                regResult.valorBool = tpExp1.valorString.charAt(0) <= tpExp2.valorString.charAt(0);
                break;
                case MENOR_IGUAL :
                pw.println("\u005ct LT");
                regResult.valorBool = tpExp1.valorString.charAt(0) <= tpExp2.valorString.charAt(0);
                break;
                default :
                ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
                ", columna " + token.beginColumn + "  - No se puede" +
                " utilizar el operador relacional " + op.getOperadorRelacional().toString() +
                " sobre caracteres");
              }
            }
            else
            {
              switch (op.getOperadorRelacional())
              {
                case IGUAL :
                pw.println("\u005ct EQ");
                break;
                case NO_IGUAL :
                pw.println("\u005ct NEQ");
                break;
                case MAYOR :
                pw.println("\u005ct GT");
                break;
                case MAYOR_IGUAL :
                pw.println("\u005ct GTE");
                break;
                case MENOR :
                pw.println("\u005ct LT");
                break;
                case MENOR_IGUAL :
                pw.println("\u005ct LTE");
                break;
                default :
                ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
                ", columna " + token.beginColumn + "  - No se puede" +
                " utilizar el operador relacional " + op.getOperadorRelacional().toString() +
                " sobre caracteres");
              }
            }
            break;
            case BOOLEANO :
            regResult.setTipo(Simbolo.Tipo_variable.BOOLEANO);
            ok = tpExp2.getTipo() == Simbolo.Tipo_variable.BOOLEANO;
            if (!ok)
            {
              regResult.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
            }
            else if (tpExp1.getSimbolo() == Simbolo.Tipo_simbolo.CONST
            && tpExp2.getSimbolo() == Simbolo.Tipo_simbolo.CONST)
            {
              constantes = true;
              switch (op.getOperadorRelacional())
              {
                case IGUAL :
                regResult.valorBool = tpExp1.valorBool == tpExp2.valorBool;
                pw.println("\u005ct EQ");
                break;
                case NO_IGUAL :
                pw.println("\u005ct NEQ");
                regResult.valorBool = tpExp1.valorBool != tpExp2.valorBool;
                break;
                default :
                ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
                ", columna " + token.beginColumn + "  - No se puede" +
                " utilizar el operador " + op.getOperadorRelacional().toString() +
                " sobre una booleano");
              }
            }
            else
            {
              switch (op.getOperadorRelacional())
              {
                case IGUAL :
                pw.println("\u005ct EQ");
                break;
                case NO_IGUAL :
                pw.println("\u005ct NEQ");
                break;
                default :
                ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
                ", columna " + token.beginColumn + "  - No se puede" +
                " utilizar el operador relacional " + op.getOperadorRelacional().toString() +
                " sobre caracteres");
              }
            }
            break;
            case DESCONOCIDO :
            regResult.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
            break;
            default :
            ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
            ", columna " + token.beginColumn + "  - El operador relacional es" +
            " desconocido");
          }
        }
        if (ok && !constantes)
        {
          regResult.setExpr_compuesta(true);
        }
      }
      }
      if (tpExp2 == null)
      {
        {if (true) return tpExp1;}
      }
      else
      {
        {if (true) return regResult;}
      }
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

  static final public TipoOperador operador_relacional() throws ParseException {
  TipoOperador op = new TipoOperador();
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tIGUAL:
        jj_consume_token(tIGUAL);
      op.setOperadorRelacional(TipoOperador.Tipo_Operador_Relacional.IGUAL);
      {if (true) return op;}
        break;
      case tMENOR:
        jj_consume_token(tMENOR);
      op.setOperadorRelacional(TipoOperador.Tipo_Operador_Relacional.MENOR);
      {if (true) return op;}
        break;
      case tMEI:
        jj_consume_token(tMEI);
      op.setOperadorRelacional(TipoOperador.Tipo_Operador_Relacional.MENOR_IGUAL);
      {if (true) return op;}
        break;
      case tNI:
        jj_consume_token(tNI);
      op.setOperadorRelacional(TipoOperador.Tipo_Operador_Relacional.NO_IGUAL);
      {if (true) return op;}
        break;
      case tMAI:
        jj_consume_token(tMAI);
      op.setOperadorRelacional(TipoOperador.Tipo_Operador_Relacional.MAYOR_IGUAL);
      {if (true) return op;}
        break;
      case tMAYOR:
        jj_consume_token(tMAYOR);
      op.setOperadorRelacional(TipoOperador.Tipo_Operador_Relacional.MAYOR);
      {if (true) return op;}
        break;
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

  static final public TipoOperador operador_aditivo() throws ParseException {
  TipoOperador op = new TipoOperador();
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tPLUS:
        jj_consume_token(tPLUS);
      op.setOperadorAditivo(TipoOperador.Tipo_Operador_Aditivo.SUMA);
      {if (true) return op;}
        break;
      case tMINUS:
        jj_consume_token(tMINUS);
      op.setOperadorAditivo(TipoOperador.Tipo_Operador_Aditivo.RESTA);
      {if (true) return op;}
        break;
      case tOR:
        jj_consume_token(tOR);
      op.setOperadorAditivo(TipoOperador.Tipo_Operador_Aditivo.OR);
      {if (true) return op;}
        break;
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

  static final public RegistroExp expresion_simple() throws ParseException {
  RegistroExp regTerm1 = null, regTerm2 = null, regResult = null;
  TipoOperador op;
  boolean ok;
  boolean constantes = false;
    try {
      regTerm1 = termino();
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tPLUS:
        case tMINUS:
        case tOR:
          ;
          break;
        default:
          jj_la1[11] = jj_gen;
          break label_5;
        }
        op = operador_aditivo();
        regTerm2 = termino();
      regResult = new RegistroExp();
      ok = true;
      if (op.getOperadorAditivo() == TipoOperador.Tipo_Operador_Aditivo.OR)
      {
        ok = regTerm1.getTipo() == Simbolo.Tipo_variable.BOOLEANO
        && regTerm2.getTipo() == Simbolo.Tipo_variable.BOOLEANO;
        if (!ok)
        {
          ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
          ", columna " + token.beginColumn + "  - Incompatibilidad de expresiones en operacion: " +
          regTerm1.getTipo().toString() + " y " + regTerm2.getTipo().toString());
          regResult.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
        }
        else
        {
          if (regTerm1.getTipo() == Simbolo.Tipo_variable.DESCONOCIDO
          || regTerm2.getTipo() == Simbolo.Tipo_variable.DESCONOCIDO)
          {
            regResult.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
          }
          else
          {
                regResult.setTipo(Simbolo.Tipo_variable.BOOLEANO);
            pw.println("\u005ct OR");
            if (regTerm1.getSimbolo() == Simbolo.Tipo_simbolo.CONST
            && regTerm2.getSimbolo() != Simbolo.Tipo_simbolo.CONST)
            {
              constantes = true;
              regResult.setSimbolo(Simbolo.Tipo_simbolo.CONST);
              regResult.valorBool = regTerm1.valorBool
            | regTerm2.valorBool;
            }
          }
        }
      }
      else
      {
        ok = regTerm1.getTipo() == Simbolo.Tipo_variable.ENTERO
        && regTerm2.getTipo() == Simbolo.Tipo_variable.ENTERO;
        if (!ok)
        {
          ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
          ", columna " + token.beginColumn + "  - Incompatibilidad de expresiones en operacion: " +
          regTerm1.getTipo().toString() + " y " + regTerm2.getTipo().toString());
          regResult.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
        }
        else if (regTerm1.getTipo() == Simbolo.Tipo_variable.DESCONOCIDO
        && regTerm2.getTipo() == Simbolo.Tipo_variable.DESCONOCIDO)
        {
          regResult.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
        }
        else
        {
          regResult.setTipo(Simbolo.Tipo_variable.ENTERO);
          if (DesbordamientoEnteros.hayDesbordamientoEntero(regTerm1.getValorEnt())
          || DesbordamientoEnteros.hayDesbordamientoEntero(regTerm2.getValorEnt()))
          {
            ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
            ", columna " + token.beginColumn + "  - Valor fuera del rango");
            regResult.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
          }
          else
          {
            if (regTerm1.getSimbolo() == Simbolo.Tipo_simbolo.CONST
            && regTerm2.getSimbolo() == Simbolo.Tipo_simbolo.CONST)
            {
              constantes = true;
              regResult.setSimbolo(Simbolo.Tipo_simbolo.CONST);
              switch (op.getOperadorAditivo())
              {
                case SUMA :
                pw.println("\u005ct PLUS");
                regResult.valorEnt = regTerm1.valorEnt + regTerm2.valorEnt;
                break;
                case RESTA :
                pw.println("\u005ct SBT");
                regResult.valorEnt = regTerm1.valorEnt - regTerm2.valorEnt;
                break;
                default :
                ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
                ", columna " + token.beginColumn + "  - Operador aditivo desconocido");
              }
            }
            else
            {
              switch (op.getOperadorAditivo())
              {
                case SUMA :
                pw.println("\u005ct PLUS");
                break;
                case RESTA :
                pw.println("\u005ct SBT");
                break;
                default :
                ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
                ", columna " + token.beginColumn + "  - Operador aditivo desconocido");
              }
            }
          }
        }
      }
      if (ok && !constantes)
      {
        regResult.setExpr_compuesta(true);
      }
      }
      if (regTerm2 == null)
      {
        {if (true) return regTerm1;}
      }
      else
      {
        {if (true) return regResult;}
      }
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

  static final public RegistroExp termino() throws ParseException {
  RegistroExp tpFactor1 = null, tpFactor2 = null, regResult = null;
  TipoOperador op;
  boolean ok;
  boolean constantes = false;
    try {
      tpFactor1 = factor();
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tMULTIPLY:
        case tDIVIDE:
        case tAND:
        case tMOD:
        case tDIV:
          ;
          break;
        default:
          jj_la1[12] = jj_gen;
          break label_6;
        }
        op = operador_multiplicativo();
        tpFactor2 = factor();
      regResult = new RegistroExp();
      if (op.getOperadorMultiplicativo() == TipoOperador.Tipo_Operador_Multiplicativo.AND)
      {
        ok = tpFactor1.getTipo() == Simbolo.Tipo_variable.BOOLEANO
        && tpFactor2.getTipo() == Simbolo.Tipo_variable.BOOLEANO;
        if (!ok)
        {
          ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
          ", columna " + token.beginColumn + "  - Incompatibilidad de expresiones en operacion: " +
          tpFactor1.getTipo().toString() + " y " + tpFactor2.getTipo().toString());
          regResult.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
        }
        else if (tpFactor2.getTipo() == Simbolo.Tipo_variable.DESCONOCIDO
        || tpFactor2.getTipo() == Simbolo.Tipo_variable.DESCONOCIDO)
        {
          regResult.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
        }
        else
        {
          regResult.setTipo(Simbolo.Tipo_variable.BOOLEANO);
          pw.println("\u005ct AND");
          if (tpFactor1.getSimbolo() == Simbolo.Tipo_simbolo.CONST
          && tpFactor2.getSimbolo() == Simbolo.Tipo_simbolo.CONST)
          {
            regResult.valorBool = tpFactor1.valorBool & tpFactor2.valorBool;
            regResult.setSimbolo(Simbolo.Tipo_simbolo.CONST);
          }
        }
      }
      else
      {
        ok = tpFactor1.getTipo() == Simbolo.Tipo_variable.ENTERO
        && tpFactor2.getTipo() == Simbolo.Tipo_variable.ENTERO;
        if (!ok)
        {
          ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
          ", columna " + token.beginColumn + "  - Incompatibilidad de expresiones en operacion: " +
          tpFactor1.getTipo().toString() + " y " + tpFactor2.getTipo().toString());
          regResult.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
        }
        else
        {
          regResult.setTipo(Simbolo.Tipo_variable.ENTERO);
          if (DesbordamientoEnteros.hayDesbordamientoEntero(tpFactor1.valorEnt)
          || DesbordamientoEnteros.hayDesbordamientoEntero(tpFactor2.valorEnt))
          {
            ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
            ", columna " + token.beginColumn + "  - Valor fuera del rango");
            regResult.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
          }
          else
          {
            if (tpFactor1.getSimbolo() == Simbolo.Tipo_simbolo.CONST
            && tpFactor2.getSimbolo() == Simbolo.Tipo_simbolo.CONST)
            {
              constantes = true;
              regResult.setSimbolo(Simbolo.Tipo_simbolo.CONST);
              switch (op.getOperadorMultiplicativo())
              {
                case MULTIPLICACION :
                pw.println("\u005ct TMS");
                regResult.valorEnt = tpFactor1.valorEnt * tpFactor2.valorEnt;
                break;
                case DIVISION :
                pw.println("\u005ct DIV");
                if (tpFactor2.valorEnt == 0)
                {
                  ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
                  ", columna " + token.beginColumn + "  - Division por 0");
                  regResult.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
                }
                else
                {
                  regResult.valorEnt = tpFactor1.valorEnt / tpFactor2.valorEnt;
                }
                break;
                case MOD :
                pw.println("\u005ct MOD");
                if (tpFactor2.valorEnt == 0)
                {
                  ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
                  ", columna " + token.beginColumn + "  - Modulo por 0");
                  regResult.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
                }
                else
                {
                  regResult.valorEnt = tpFactor1.valorEnt % tpFactor2.valorEnt;
                }
                break;
                default :
                ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
                ", columna " + token.beginColumn + "  - Operador multiplicativo desconocido");
              }
            }
            else
            {
              switch (op.getOperadorMultiplicativo())
              {
                case MULTIPLICACION :
                pw.println("\u005ct TMS");
                break;
                case DIVISION :
                pw.println("\u005ct DIV");
                break;
                case MOD :
                pw.println("\u005ct MOD");
                break;
                default :
                ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
                ", columna " + token.beginColumn + "  - Operador multiplicativo desconocido");
              }
            }
          }
        }
      }
      if (ok && !constantes)
      {
        regResult.setExpr_compuesta(true);
      }
      }
      if (tpFactor2 == null)
      {
        {if (true) return tpFactor1;}
      }
      else
      {
        {if (true) return regResult;}
      }
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

  static final public TipoOperador operador_multiplicativo() throws ParseException {
  TipoOperador op = new TipoOperador();
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tMULTIPLY:
        jj_consume_token(tMULTIPLY);
      op.setOperadorMultiplicativo(TipoOperador.Tipo_Operador_Multiplicativo.MULTIPLICACION);
      {if (true) return op;}
        break;
      case tDIVIDE:
        jj_consume_token(tDIVIDE);
      op.setOperadorMultiplicativo(TipoOperador.Tipo_Operador_Multiplicativo.DIVISION);
      {if (true) return op;}
        break;
      case tDIV:
        jj_consume_token(tDIV);
      op.setOperadorMultiplicativo(TipoOperador.Tipo_Operador_Multiplicativo.DIVISION);
      {if (true) return op;}
        break;
      case tMOD:
        jj_consume_token(tMOD);
      op.setOperadorMultiplicativo(TipoOperador.Tipo_Operador_Multiplicativo.MOD);
      {if (true) return op;}
        break;
      case tAND:
        jj_consume_token(tAND);
      op.setOperadorMultiplicativo(TipoOperador.Tipo_Operador_Multiplicativo.AND);
      {if (true) return op;}
        break;
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

  static final public RegistroExp factor() throws ParseException {
  RegistroExp tpFactor, tpExp;
  RegistroExp result = new RegistroExp();
  Token t;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tNOT:
        jj_consume_token(tNOT);
        tpFactor = factor();
      if ((tpFactor.getTipo() != Simbolo.Tipo_variable.BOOLEANO)
      && (tpFactor.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO))
      {
        ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
        ", columna " + token.beginColumn + "  - Tipo " + tpFactor.getTipo() + " incompatible con " +
        " operador <>. Se esperaba BOOLEANO ");
        result.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
      }
      else
      {
        pw.println("\u005ct NGB");
        result.setTipo(Simbolo.Tipo_variable.BOOLEANO);
      }
      {if (true) return result;}
        break;
      case tMINUS:
        jj_consume_token(tMINUS);
        tpFactor = factor();
      if ((tpFactor.getTipo() != Simbolo.Tipo_variable.ENTERO)
      && (tpFactor.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO))
      {
        ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
        ", columna " + token.beginColumn + "  - Tipo " + tpFactor.getTipo().toString() +
        " incompatible con operador -. Se esperaba ENTERO");
        result.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
      }
      else
      {
        pw.println("\u005ct NGBI");
        result.setTipo(Simbolo.Tipo_variable.ENTERO);
      }
      {if (true) return result;}
        break;
      case tPARENTESIS_IZDA:
        jj_consume_token(tPARENTESIS_IZDA);
        tpExp = expresion();
        jj_consume_token(tPARENTESIS_DCHA);
      {if (true) return tpExp;}
        break;
      case tENTACAR:
        t = jj_consume_token(tENTACAR);
        jj_consume_token(tPARENTESIS_IZDA);
        tpExp = expresion();
        jj_consume_token(tPARENTESIS_DCHA);
      if ((tpExp.getTipo() != Simbolo.Tipo_variable.ENTERO)
      && (tpExp.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO))
      {
        ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
        ", columna " + token.beginColumn + "  - Argumento de tipo " + tpExp.getTipo().toString() +
        " incompatible en funcion ENTACAR. Se esperaba ENTERO");
        result.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
      }
      else
      {
        int valor = tpExp.getValorEnt();
        if (ErrorSemantico.hayDesbordamientoEntacar(valor))
        {
          ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
          ", columna " + token.beginColumn + "  - La operacion ENTACAR debe recibir un par\u00e1metro " +
          "del tipo entero comprendido entre 0 y 255");
        }
        else
        {
          if (tpExp.getSimbolo() == Simbolo.Tipo_simbolo.CONST)
          {
            result.setValorString(String.valueOf((char) valor));
            result.setTipo(Simbolo.Tipo_variable.CHAR);
          }
          result.setTipo(Simbolo.Tipo_variable.CHAR);
        }
      }
      {if (true) return result;}
        break;
      case tCARAENT:
        jj_consume_token(tCARAENT);
        jj_consume_token(tPARENTESIS_IZDA);
        tpExp = expresion();
        jj_consume_token(tPARENTESIS_DCHA);
      if ((tpExp.getTipo() != Simbolo.Tipo_variable.CHAR)
      && (tpExp.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO))
      {
        ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
        ", columna " + token.beginColumn + "  - Argumento de tipo " + tpExp.getTipo().toString() +
        " incompatible en funcion CARAENT. Se esperaba CARACTER");
        result.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
      }
      else
      {
        if (tpExp.getSimbolo() == Simbolo.Tipo_simbolo.CONST)
        {
          char cadena = tpExp.valorString.charAt(0);
          result.setValorEnt((int) cadena);
        }
        result.setTipo(Simbolo.Tipo_variable.ENTERO);
      }
      {if (true) return result;}
        break;
      case tIDENTIFICADOR:
        t = jj_consume_token(tIDENTIFICADOR);
      Simbolo s;
      s = tabla.buscar_simbolo(t.image);
      if (s == null)
      {
        ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
        ", columna " + token.beginColumn + "  - Variable " + t.image + " no definida");
        tabla.introducir_variable(t.image, Simbolo.Tipo_variable.DESCONOCIDO, nivel, 0);
        result.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
      }
      else if (s.es_Simbolo_Accion())
      {
        ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
        ", columna " + token.beginColumn + "  - La accion " + s.getNombre() + " no puede " +
        " formar parte de una expresion");
        tabla.introducir_variable(t.image, Simbolo.Tipo_variable.DESCONOCIDO, nivel, 0);
        result.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
      }
      else
      {
        result.setTipo(s.getVariable());
        result.setClase(s.getParametro());
        pw.println("; Acceso a la variable " + s.getNombre().toUpperCase() + ".");
        pw.println("\u005ct SRF   " + (nivel - s.getNivel()) + "  " + s.getDir());

        if (flag_invocacion)
        {
                if (s.es_Simbolo_Parametro() && s.es_Parametro_Valor())
                {
                                pw.println("\u005ct DRF");
                        }
                }
                else
                {
                        pw.println("\u005ct DRF");
                        if (derechaAsig && s.es_Simbolo_Parametro() && s.es_Parametro_Referencia())
                        {
                            pw.println("\u005ct DRF");
                        }
                }
      }
      {if (true) return result;}
        break;
      case tCONSTANTE_NUMERICA:
        t = jj_consume_token(tCONSTANTE_NUMERICA);
      int valor = Integer.parseInt(t.image);
      result.setValorEnt(valor);
      result.setTipo(Simbolo.Tipo_variable.ENTERO);
      result.setSimbolo(Simbolo.Tipo_simbolo.CONST);
      pw.println("\u005ct STC   " + t.image);
      {if (true) return result;}
        break;
      case tCONSTCHAR:
        t = jj_consume_token(tCONSTCHAR);
      if (t.image.length() > 3)
      {
        ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
        ", columna " + token.beginColumn + "  - No se puede usar el caracter " + t.image +
        " en una expresion");
      }
      else
      {
        result.setSimbolo(Simbolo.Tipo_simbolo.CONST);
        result.valorString = String.valueOf(t.image.charAt(1));
      }
      pw.println("\u005ct STC   " + t.image);
      result.setTipo(Simbolo.Tipo_variable.CHAR);
      {if (true) return result;}
        break;
      case tCONSTCAD:
        t = jj_consume_token(tCONSTCAD);
      if (t.image.length() > 3)
      {
        ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
        ", columna " + token.beginColumn + "  - No se puede usar la cadena " + t.image +
        " en una expresion");
      }
      else
      {
        result.setSimbolo(Simbolo.Tipo_simbolo.CONST);
        result.valorString = String.valueOf(t.image.charAt(1));
      }
      pw.println("\u005ct STC   " + t.image);
      result.setTipo(Simbolo.Tipo_variable.CADENA);
      {if (true) return result;}
        break;
      case tTRUE:
        jj_consume_token(tTRUE);
      result.setSimbolo(Simbolo.Tipo_simbolo.CONST);
      result.setValorBool(true);
      result.setTipo(Simbolo.Tipo_variable.BOOLEANO);
      pw.println("\u005ct STC   1");
      {if (true) return result;}
        break;
      case tFALSE:
        jj_consume_token(tFALSE);
      result.setSimbolo(Simbolo.Tipo_simbolo.CONST);
      result.setValorBool(false);
      result.setTipo(Simbolo.Tipo_variable.BOOLEANO);
      pw.println("\u005ct STC   0");
      {if (true) return result;}
        break;
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

  static final public void seleccion() throws ParseException {
  RegistroExp tpExp;
  String etiqSINO = null, etiqFIN;
    try {
      jj_consume_token(tSI);
      pw.println("; SI.");
      tpExp = expresion();
      if ((tpExp.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
      && (tpExp.getTipo() != Simbolo.Tipo_variable.BOOLEANO))
      {
        ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
        ", columna " + token.beginColumn + "  - La condicion en la seleccion debe ser un booleano");
      }
      else
      {
        etiqSINO = etiq.nueva_etiqueta();
        pw.println("\u005ct JMF " + etiqSINO);
      }
      jj_consume_token(tENT);
      pw.println("; ENT.");
      lista_sentencias();
      etiqFIN = etiq.nueva_etiqueta();
      pw.println("\u005ct JMP " + etiqFIN);
      pw.println(etiqSINO + ":");
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tSI_NO:
        jj_consume_token(tSI_NO);
      pw.println("; SI_NO.");
        lista_sentencias();
        break;
      default:
        jj_la1[15] = jj_gen;
        ;
      }
      jj_consume_token(tFSI);
      pw.println(etiqFIN + ":");
      pw.println("; Fin SI");
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
  }

  static final public void declaracion_acciones() throws ParseException {
    try {
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tACCION:
          ;
          break;
        default:
          jj_la1[16] = jj_gen;
          break label_7;
        }
        declaracion_accion();
      }
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
  }

  static final public void declaracion_accion() throws ParseException {
  Simbolo s;
    try {
      s = cabecera_accion();
      jj_consume_token(tPUNTYCOM);
      declaracion_variables();
      declaracion_acciones();
      bloque_sentencias(s);
      dir = s.getDir();
      pw.println("; Fin de la accion / funcion " + s.getNombre().toUpperCase() + ".");
      pw.println("\u005ct CSF");

      tabla.eliminar_variables(nivel);
      tabla.eliminar_acciones(nivel);
      tabla.eliminar_parametros_ocultos(nivel);
      nivel--;

      incrementar_pila();
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
  }

  static final public Simbolo cabecera_accion() throws ParseException {
  Token tId = null;
  Simbolo s, sAccion = null;
  Simbolo.Tipo_simbolo tp_Sim;
  boolean ok = false;
  LinkedList < LinkedList < Simbolo > > listaDeParametros = new LinkedList < LinkedList < Simbolo > > ();
  LinkedList < Simbolo > listaAuxiliar = new LinkedList < Simbolo > ();
    try {
      jj_consume_token(tACCION);
      tId = jj_consume_token(tIDENTIFICADOR);
      s = tabla.buscar_simbolo(tId.image);
      if ((s == null) || (s.getNivel() != nivel))
      {
        s = tabla.introducir_accion(tId.image, nivel, dir);
        ok = true;
        String etiqAccion = etiq.nueva_etiqueta();
        s.setEtiqueta(etiqAccion);
      }
      else
      {
        ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
        ", columna " + token.beginColumn + "  - Accion " + s.getNombre() + " duplicada");
        ok = false;
      }
      nivel++;
      iniciar_pila();
      sAccion = s;
      listaDeParametros = parametros_formales(tId);
      if (ok)
      {
        for (int i = 0; i < listaDeParametros.size(); i++)
        {
          s.anyadirParametrosAccion(listaDeParametros.get(i), dir);
          incrementar_pila();
        }
        tabla.limpiarListaParametros();
      }
      {if (true) return sAccion;}
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

  static final public LinkedList < LinkedList < Simbolo > > parametros_formales(Token t) throws ParseException {
  LinkedList < LinkedList < Simbolo > > parametros = new LinkedList < LinkedList < Simbolo > > ();
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tPARENTESIS_IZDA:
        parametros = lista_parametros();
      tabla.asignarListaParametros(parametros);
        break;
      default:
        jj_la1[17] = jj_gen;
        ;
      }
      {if (true) return tabla.getListasParametros();}
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

  static final public LinkedList < LinkedList < Simbolo > > lista_parametros() throws ParseException {
  LinkedList < LinkedList < Simbolo > > listaGlobal = new LinkedList < LinkedList < Simbolo > > ();
  LinkedList < Simbolo > lista = new LinkedList < Simbolo > ();
    try {
      jj_consume_token(tPARENTESIS_IZDA);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tVAL:
      case tREF:
        lista = parametros();
      listaGlobal.add(lista);
        label_8:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case tPUNTYCOM:
            ;
            break;
          default:
            jj_la1[18] = jj_gen;
            break label_8;
          }
          jj_consume_token(tPUNTYCOM);
          lista = parametros();
      listaGlobal.add(lista);
        }
        jj_consume_token(tPARENTESIS_DCHA);
      {if (true) return listaGlobal;}
        break;
      case tPARENTESIS_DCHA:
        jj_consume_token(tPARENTESIS_DCHA);
      {if (true) return listaGlobal;}
        break;
      default:
        jj_la1[19] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

  static final public LinkedList < Simbolo > parametros() throws ParseException {
  Simbolo s;
  Simbolo.Clase_parametro cl_Param;
  Simbolo.Tipo_variable tipo_Var;
  LinkedList < Simbolo > lista = new LinkedList < Simbolo > ();
  LinkedList < String > listaIdentificadores = new LinkedList < String > ();
    try {
      cl_Param = clase_parametros();
      tipo_Var = tipos_variables();
      listaIdentificadores = identificadores();
      int dimension = listaIdentificadores.size();
      String identificadorActual;
      for (int i = 0; i < dimension; i++)
      {
        identificadorActual = listaIdentificadores.get(i);
        s = tabla.introducir_parametro(identificadorActual, tipo_Var, cl_Param, nivel, dir);
        if (s != null)
        {
          lista.add(s);
        }
        else
        {
          ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
          ", columna " + token.beginColumn + "  - Parametro repetido " + identificadorActual);
        }
      }
      {if (true) return lista;}
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

  static final public int declaracion_variables() throws ParseException {
  Token t;
  int total = 0, aux = 0;
    try {
      label_9:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tENTERO:
        case tBOOLEANO:
        case tCARACTER:
          ;
          break;
        default:
          jj_la1[20] = jj_gen;
          break label_9;
        }
        aux = declaracion();
        t = jj_consume_token(tPUNTYCOM);
      total += aux;
      }
      {if (true) return total;}
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

  static final public Simbolo.Tipo_variable tipos_variables() throws ParseException {
  Token t;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tENTERO:
        t = jj_consume_token(tENTERO);
        break;
      case tCARACTER:
        t = jj_consume_token(tCARACTER);
        break;
      case tBOOLEANO:
        t = jj_consume_token(tBOOLEANO);
        break;
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch (t.kind)
      {
        case tENTERO :
        {if (true) return Simbolo.Tipo_variable.ENTERO;}
        break;
        case tCARACTER :
        {if (true) return Simbolo.Tipo_variable.CHAR;}
        break;
        case tCONSTCAD :
        {if (true) return Simbolo.Tipo_variable.CADENA;}
        break;
        case tBOOLEANO :
        {if (true) return Simbolo.Tipo_variable.BOOLEANO;}
        break;
        default :
        {if (true) return Simbolo.Tipo_variable.DESCONOCIDO;}
      }
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

  static final public int declaracion() throws ParseException {
  Token t;
  Simbolo.Tipo_variable tp_Var;
  LinkedList < String > lista = new LinkedList < String > ();
  String identificadorActual;
  Simbolo s;
    try {
      tp_Var = tipos_variables();
      lista = identificadores();
      int dimension = lista.size();
      for (int i = 0; i < dimension; i++)
      {
        identificadorActual = lista.get(i);
        s = tabla.introducir_variable(identificadorActual, tp_Var, nivel, dir);
        if (i <= dimension - 1)
        {
          incrementar_pila();
        }
        if (s == null)
        {
          ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
          ", columna " + token.beginColumn + "  - Variable repetida " + identificadorActual);
        }
      }
      {if (true) return lista.size();}
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

  static final public LinkedList < String > identificadores() throws ParseException {
  Token t;
  LinkedList < String > listaIdentificadores = new LinkedList < String > ();
    try {
      t = jj_consume_token(tIDENTIFICADOR);
      listaIdentificadores.add(t.image);
      label_10:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tCOMA:
          ;
          break;
        default:
          jj_la1[22] = jj_gen;
          break label_10;
        }
        jj_consume_token(tCOMA);
        t = jj_consume_token(tIDENTIFICADOR);
      listaIdentificadores.add(t.image);
      }
      {if (true) return listaIdentificadores;}
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

  static final public Simbolo.Clase_parametro clase_parametros() throws ParseException {
  Token t;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tVAL:
        t = jj_consume_token(tVAL);
        break;
      case tREF:
        t = jj_consume_token(tREF);
        break;
      default:
        jj_la1[23] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      if (t.kind == tVAL)
      {
        {if (true) return Simbolo.Clase_parametro.VAL;}
      }
      else if (t.kind == tREF)
      {
        {if (true) return Simbolo.Clase_parametro.REF;}
      }
      else
      {
        ErrorSemantico.deteccionErrorSemantico("linea " + token.beginLine +
        ", columna " + token.beginColumn + "  - La clase de parametro no es correcta");
      }
    } catch (ParseException e) {
    ErrorSintactico.deteccionErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public CompiladorTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[24];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x88000000,0x88000000,0x80000,0x0,0x0,0x0,0x400400,0x0,0x7e000,0x7e000,0x200600,0x200600,0x101800,0x101800,0x400400,0x20000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x100006,0x100006,0xa00000,0x400000,0x160400,0x800000,0x9e0f00,0x400000,0x0,0x0,0x0,0x0,0x18,0x18,0x9e0f00,0x0,0x1000,0x800000,0x200000,0x1006000,0xe0,0xe0,0x400000,0x6000,};
   }

  /** Constructor with InputStream. */
  public Compilador(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Compilador(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new CompiladorTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Compilador(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new CompiladorTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Compilador(CompiladorTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(CompiladorTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[57];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 24; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 57; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
