./test_bzip3.sh test/big.txt
./test_bzip3.sh test/BuildToolPlugins.html
./test_bzip3.sh test/caustica.ppm
./test_bzip3.sh test/Compilador.java
./test_bzip3.sh test/cornellBox.ppm
./test_bzip3.sh test/fields.c
./test_bzip3.sh test/lcet10.txt
./test_bzip3.sh test/makefile
./test_bzip3.sh test/plrabn12.txt
./test_bzip3.sh test/shakespeare.txt